name: silverfish
version: ${version}
main: osaki.silverfish.Silverfish
api-version: '1.21'

commands:
  tpa:
    description: Send teleport request
    usage: /tpa <player>

  tpaccept:
    description: Accept teleport request
    usage: /tpaccept <player>

  tpdeny:
    description: Deny teleport request
    usage: /tpdeny <player>

  suicide:
    description: Commit suicide
    usage: /suicide
    aliases:
      - kms

  afk:
    description: Go into AFK mode
    usage: /afk

  wp:
    description: Teleport to a waypoint
    usage: /wp <waypoint-name>

  wpset:
    description: Set waypoint
    usage: /wpset <waypoint-name>

  wpdel:
    description: Delete waypoint
    usage: /wpdel <waypoint-name>

  wpls:
    description: List waypoints
    usage: /wpls