name: silverfish
version: ${version}
main: osaki.silverfish.Silverfish
api-version: '1.21'

commands:
  tpa:
    description: Send teleport request
    usage: /tpa <player>

  tpaccept:
    description: Accept teleport request
    usage: /tpaccept <player>

  tpdeny:
    description: Deny teleport request
    usage: /tpdeny <player>

  suicide:
    description: Commit suicide
    usage: /suicide
    aliases:
      - kms

  afk:
    description: Go into AFK mode
    usage: /afk